
/*
 * TIMER1_cfg.h
 *
 * Created: 9/14/2022 12:04:18 PM
 *  Author: MICHAEL
 */ 


/* TIMER0 Prescalar Options*/
/* 1- TIM1_STOP_TIMER
*  2- TIM1_NO_PRESCALAR
*  3- TIM1_8PRESCALAR
*  4- TIM1_64PRESCALAR
*  5- TIM1_256PRESCALAR
*  6- TIM1_1024PRESCALAR
*  7- TIM1_EXTERNAL_CLK_FALLING_EDGE
*  8- TIM1_EXTERNAL_CLK_FALLING_EDGE
*/

#define TIM1_SET_PRESCALAR TIM1_8PRESCALAR

/* TIM0 Mode options
*	1- TIM1_OVF_MODE 
	2- FAST_PWM_ICR1
	3- FAST_PWM_OCR1A
*/
#define TIM1_MODE TIM1_OVF_MODE

/*
TIM0 OC0 Pin Options :
	1- TIM1_0C1_DISCONNECTED
	2- TIM1_OC1_TOGGLE
	3- TIM1_OC1_CLR
	4- TIM1_OC1_SET
*/

#define TIM1_PIN_MODE TIM1_OC1_CLR


/* TIM0_PWM_MODE options :
	1- TIM1_PWM_NON_INVERTING
	2- TIM1_PWM_INVERTING 
	NOTE: NON_INVERTING -> Duty cycle Normal To OCR
		  INVERTING -> Duty cycle opposite To OCR
*/
#define TIM0_PWM_MODE TIM1_PWM_NON_INVERTING