
/*
 * TIMER_cfg.h
 *
 * Created: 9/14/2022 12:04:18 PM
 *  Author: MICHAEL
 */ 


/* TIMER0 Prescalar Options*/
/* 1- TIM0_STOP_TIMER
*  2- TIM0_NO_PRESCALAR
*  3- TIM0_8PRESCALAR
*  4- TIM0_64PRESCALAR
*  5- TIM0_256PRESCALAR
*  6- TIM0_1024PRESCALAR
*  7- TIM0_EXTERNAL_CLK_FALLING_EDGE
*  8- TIM0_EXTERNAL_CLK_FALLING_EDGE
*/

#define TIM0_SET_PRESCALAR TIM0_1024PRESCALAR

/* TIM0 Mode options
*	1- TIM0_OVF_MODE 
*	2- TIM0_CTC_MODE
	3- TIM0_FAST_PWM
	4- TIM0_PHASE_CORRECT_PWM
*/
#define TIM0_MODE TIM0_CTC_MODE

/*
TIM0 OC0 Pin Options :
	1- TIM0_0C0_DISCONNECTED
	2- TIM0_OC0_TOGGLE
	3- TIM0_OC0_CLR
	4- TIM0_OC0_SET
*/

#define TIM0_PIN_MODE TIM0_0C0_DISCONNECTED


/* TIM0_PWM_MODE options :
	1- TIM0_PWM_NON_INVERTING
	2- TIM0_PWM_INVERTING 
	NOTE: NON_INVERTING -> Duty cycle Normal To OCR
		  INVERTING -> Duty cycle opposite To OCR
*/
#define TIM0_PWM_MODE TIM0_PWM_NON_INVERTING